import logging
from io import StringIO

from myutils.config import Setup
from myutils.email import send_email
from myutils.playwright import playwright_setup

s = Setup("job_ahs")

KEYWORDS = ("psychology", "mental health")
BANNED = ("social", "aide")

old = s.read_line()

with playwright_setup() as page:
    logging.info("Getting page")
    page.goto("https://careers.albertahealthservices.ca/")

    page.get_by_role("button", name="Search").click()

    page.get_by_role("link").filter(has_text="View More").nth(0).click()
    for div in page.locator("css=form.facet_view_more").locator("css=div.filter_row").all():
        for item in div.locator("p").all():
            if "Edmonton" in item.text_content():
                item.get_by_role("checkbox").check()
    page.get_by_role("button", name="Submit").click()

    page.get_by_role("link").filter(has_text="View More").nth(1).click()
    for div in page.locator("css=form.facet_view_more").locator("css=div.filter_row").all():
        for item in div.locator("p").all():
            if any(keyword in item.text_content().lower() for keyword in KEYWORDS):
                item.get_by_role("checkbox").check()
    page.get_by_role("button", name="Submit").click()

    for job in page.locator("css=div.job_list_row").all():
        job_top = job.locator("css=a.job_link")
        title = job_top.inner_text()
        job_id = job.get_attribute("id").split("_")[-1]

        if any(ban_word in title.lower() for ban_word in BANNED):
            continue

        if job_id in old:
            continue

        logging.info(job_id, title)

        subject = f"AHS Careers: {title}"
        html = StringIO()
        html.write("The following is a new job posted on the AHS website.<br><br>")
        html.write(f"<b>{title}</b><br><br>")
        html.write(f"<b>Location:</b> {job.locator('css=span.location').inner_text()}<br>")
        html.write(f"<b>Category:</b> {job.locator('css=span.category').inner_text()}<br><br>")
        html.write(job_top.get_attribute("href"))
        html.write("<br><br><br>This email is automatically generated by a script.")

        send_email("JobPostings", subject, html.getvalue())

        s.write_line(job_id)

s.ping()
