import logging
from io import StringIO

from myutils.config import Setup
from myutils.email import send_email
from myutils.playwright import playwright_setup

s = Setup("job_epsb")

SEARCH_URL = "https://www.epsb.ca/ourdistrict/careers/exempt/"

old = s.read_line()

with playwright_setup() as page:
    logging.info("Getting search page")
    page.goto(SEARCH_URL)

    for job in page.locator("css=div.job-posting").all():
        title = job.locator("css=h3").inner_text()
        job_id = job.locator("css=h4").inner_text().split(":")[-1].strip()
        description = job.locator("p").nth(1).inner_text()

        if job_id in old:
            continue

        logging.info(job_id, title)

        subject = f"EPSB.ca: {title}"
        html = StringIO()
        html.write("The following is a new job posted on the EPSB website<br><br>")
        html.write(f"<b>Job Title:</b> {title}<br>")
        html.write(f"<b>Job ID:</b> {job_id}<br><br><br>")
        html.write(SEARCH_URL)
        html.write("<br><br>This email is automatically generated by a script.")

        send_email("JobPostings", subject, html.getvalue())

        s.write_line(job_id)

s.ping()
